### PR TITLE
[BugFix] More robust route root check

### LINKED ISSUE #633: [Bug]: i18n - Hero missing in pages with locale
### 📝 Issue Description

The hero missing in pages with locale

This happened because existing root check logic (shown below) checks for locale or project, but ignores all the more complex cases with both locale+project:

```ts
const isRoot = useMatch(() => "/:localeOrProject?", {
  localeOrProject: [...SUPPORTED_LOCALES, ...PROJECTS],
});
```

### 📋 On which page(s) it occurs

https://docs.solidjs.com/pt-br/
https://docs.solidjs.com/pt-br/solid-router

### 🤔 Expected Behavior

That the localized page looks like the english page

### 👀 Current Behavior

Hero missing

### 🖥️ Browser

Chrome 122

### LINKED ISSUE #634: [Bug]: Edit/Issue links on project roots (not Core) are broken
### 📝 Issue Description

From the project roots, the "Edit page" link doesn't work. 

### 📋 On which page(s) it occurs

Broken edit+issue links
https://docs.solidjs.com/solid-router
https://docs.solidjs.com/solid-start

### 🤔 Expected Behavior

The link should go to i.e. solid-router/index.mdx

### 👀 Current Behavior

Currently the link go to i.e. solid-router.mdx  for the Router.

### 🖥️ Browser

Chrome 122

### 📄 Additional Information

_No response_

### LINKED ISSUE #635: [Bug]: Issue creation links doesn't update on routing
### 📝 Issue Description

When navigating, the issue creation links doesn't update.

### 📋 On which page(s) it occurs

All page

### 🤔 Expected Behavior

They should update

### 👀 Current Behavior

They don't update when navigating, until a full page reload happen.

### 🖥️ Browser

Chrome 122

### 📄 Additional Information

Similar to
- #627

### PR DESCRIPTION
**Pull request by birkskyum**
I created a function that returns:

```ts
interface CurrentRouteMetaData {
	project: Project | null;
	locale: string;
	isProjectRoot: boolean;
}
```

And used it to improve the logic in the entryFile i18 helper.

This solves a few things:
- Closes #634
- Closes #635
- Closes #633

If there is desire to differentiating the heros, this function would be handy for that.

Request for review: @atilafassina

### CODE REVIEW

File: src/ui/layout.tsx [hunk 1]
```diff
@@ -22,6 +22,71 @@ import { PathMatch } from "@solidjs/router/dist/types";
...
+			returnObject.project = path as Project;
+		} else {
+			returnObject.isProjectRoot = false;
+			returnObject.project = "" as Project;
+		}
+	}
+
+	return returnObject;
+};
+
```
Comment (danieljcafonso) [inline src/ui/layout.tsx:89]: This is a small nitpick but would it make sense to move this to the helpers file? Considering it is also being imported there, it would probably be better to have it there or a separate file than increasing the size of this UI file 🤔
Let me know your thoughts please!

Aside from this comment everything else is working fine for me and this seems a great improvement 😄

Comment (birkskyum) [reply src/ui/layout.tsx:89]: That is a great idea!  I'll move it right away.

**Review by atilafassina — APPROVED** [review]
awesome work!!
Sorry it took me so long to merge it
